User list UI
harshup20/git_user_list pull request #2
Opened 2021-06-22 14:11 UTC by harshup20

implemented the presentation layer 
store the data to the hive database

2021-06-23 06:07 UTC, mayyuu commented on lib/datasource/local/git_user_list.dart
> +class UserListDataStore {
Can you please tell us the use of this UserListDataStore class

2021-06-23 06:12 UTC, mayyuu commented on lib/di/providers.dart
>  ];
Can you please explain us the use of taking BaseListViewModel and SelectedListViewModel as ChangeNotifierProvider?

2021-06-23 06:15 UTC, mayyuu commented on lib/presentation/user_list/all_user_list/list_view_model.dart
> +    var box = await Hive.openBox<UserItem>(_userBox);
Can you please try to create Hive Request class which will handel all hive related functions eg.(Hive.init,Hive.open,Hive.close).

2021-06-23 06:17 UTC, mayyuu commented on lib/presentation/user_list/selected_user/selected_user_view.dart
> +    context.watch<SelectedListViewModel>().getItem();
Can you please tell the use of context.watch<SelectedListViewModel>().getItem(); inside your build method?

2021-06-23 06:29 UTC, harshup20 commented on lib/presentation/user_list/selected_user/selected_user_view.dart
> +    context.watch<SelectedListViewModel>().getItem();
to listen only to a specific set of properties on the obtained object. It may cause the widget to rebuild if something other than name changes.

2021-06-23 07:45 UTC, naikdp7 commented on lib/datasource/remote/providers/rest/request/user_request.dart
> +      return 20;
can you reduce the batch size to 10

2021-06-23 07:47 UTC, naikdp7 commented on lib/main.dart
> +  Hive.init(directory.path);
this should in local source.dont use hive directly in main.incase in future we need to change the db other than hive then we need to change here also.so make a practice to use clean architecture properly.

2021-06-23 07:51 UTC, naikdp7 commented on lib/presentation/user_list/selected_user/selected_user_model.dart
> +  final box = await Hive.openBox<UserItem>(_userBox);
we should get this from local source not directly in presentation.make a habit of using respective source.this should be came in localsource only.no need to expose in other layers.

2021-06-23 07:51 UTC, naikdp7 requested changes
Requested changes

2021-06-29 14:03 UTC, harshup20 commented
Uploading screerecord.mp4…

2021-06-29 14:04 UTC, harshup20 commented
https://user-images.githubusercontent.com/68155750/123811501-ee8f3980-d910-11eb-8e45-626779215803.mp4

2021-07-01 10:58 UTC, closed without merging